### ISSUE TITLE
Add USDC to allowed symbols for ccxt

### ISSUE THREAD

**Issue by skirsch** [stellar/kelp#107]
// see a sample bug report here: https://github.com/stellar/kelp/issues/1

## Describe the bug
// A succinct description of the buggy behavior.
// This section includes **what** the bot is doing and **why** you think it is incorrect.

The bot aborts if use USDC.

## Expected behavior
// A succinct description of **what you expected to happen**.

I think the correct behavior in this situation is for the bot to not crash

## Frequency

The frequency is: always

## Possible Solution

This bug can be fixed by adding the popular USD surrogates to the list of symbols.. TUSD, USDC, GUSD, HUSD.

## Your Environment
// Run `kelp version` to get the version and build information and paste it here
//   version: v1.0.0-rc1
//   git hash: 1bcc4e9fa4012867a549472dbdf61cb008041305
//   build date: 20180813T013016Z
//   GOOS: linux
//   GOARCH: amd64

...

## Context
USDT prices are inflated because USDT is so flakey. So it's imposssible to get a real USD price quote unless you use USDC, but you can't because the bot crashes. please add these symbols to the ccxt table

## Attachments
// Attach any relevant configuration files, logs, tx hashes, etc. here.

**Comment by nikhilsaraf** [comment]
approved PR to add USDC https://github.com/stellar/kelp/pull/111
@skirsch / @paul-token please add any other USD tokens you'll may be interested in trading with a similar PR. thanks!

**Comment by nikhilsaraf** [comment]
closing this out. If there are any more USD tokens you want to add or any other tokens, feel free to submit a PR.
