### ISSUE TITLE
accomodate additional ccxt parameters

### ISSUE THREAD

**Issue by Reidmcc** [stellar/kelp#139]
## Desired Behavior

Some ccxt exchanges require additional parameters in API requests; e.g. Coinbase Pro requires a passphrase in an http header as well as an API key and secret. Currently Kelp doesn't have a way to get those parameters through ccxt and into the API requests.

## Impact

Without this capability Kelp can't trade on Coinbase Pro, or any other exchanges that require additional parameters.

## Feature Suggestion

We can implement this by adding a place to specify additional ccxt parameters in the trader configuration file to pass to the local ccxt server and add code to Kelp to pass them. Pull request incoming.

## Additional context

I originally tried to accomplish this by adding capability to append http headers in support/sdk/ccxt.go. This didn't work because it turns out the error was coming from the ccxt local server; the request never went to Coinbase. Ccxt knows about the Coinbase passphrase and requires it before it will send requests. The correct method was to pass parameters to ccxt in the format it requires. 

I ended up leaving the header appending feature in because it will allow users to add any headers that ccxt *doesn't* know about.

**Comment by nikhilsaraf** [comment]
closed by https://github.com/stellar/kelp/pull/140
