### ISSUE TITLE
"Asset converter could not recognize string" error when trading on kraken

### ISSUE THREAD

**Issue by joaofrp** [stellar/kelp#143]
## Describe the bug
I'm getting the following error when trading on kraken: "could not fetch liability for asset 'quote ', error = error fetching open orders in LoadOffersHack: base asset could not be converted: asset converter could not recognize string: ETH" when trading ETH/BTC on kraken. I've noticed that this error only happens in the second iteration, when there are orders placed. If there are no orders placed, kelp is able to put the orders of all my five levels.

## Expected behavior
The bot should recognize the string as it is the same that it used to place the first orders during the first iteration of the algorithm.

## Frequency
The frequency is always (when there are orders placed).

## Steps To Reproduce
Here are the steps to reproduce the issue:

1. Run kelp configured to trade ETH/BTC (haven't tested other pairs) on kraken. 

2. Let the bot put the orders of your levels. Once there are orders placed and the bot runs for the second time, this error appears and keeps appearing until all the orders are consumed. Then the bot manages to put new orders.

## Your Environment
version: master:v1.6.0
 git branch: master
 git hash: 761e114ee60ead6fb08482227b21fa8e8d39b696
 build date: 20190329T234001Z
 GOOS: linux
 GOARCH: arm

## Context
This error prevents the bot from adjusting the orders according to the configuration files.

## Attachments
[kelp_log.txt](https://github.com/stellar/kelp/files/3028473/kelp_log.txt)

**Comment by joaofrp** [comment]
Just to add that using the ccxt-kraken exchange integration resuts on the same error.

**Comment by nikhilsaraf** [comment]
@joaofrp this should be fixed now -- can you pull from master and let me know if it's working for you? It was working for me on ccxt-kraken.

**Comment by joaofrp** [comment]
@nikhilsaraf now i'm getting a different error: "error fetching open orders in LoadOffersHack: cannot load open orders for Kraken: Could not execute request #5! (Response Content-Type is 'text/html', but should be 'application/json'.)" 
It happens again during kelp's second run (in the first run it was able to put the orders fine, just like before). Maybe this is on kraken's side?

**Comment by nikhilsaraf** [comment]
Yes, you should set your delete cycles threshold so it doesn’t error out in these situations. Ccxt-Kraken is more stable than the native kraken integration
