### ISSUE TITLE
Add precision overrides

### ISSUE THREAD

**Issue by Reidmcc** [stellar/kelp#152]
## Desired Behavior
Users should be able to set Kelp's volume and price precision, especially because ccxt has the wrong values for some exchanges

## Impact
This will allow users to trade on exchanges with unknown or incorrect precision values.

## Feature Suggestion
We can do this by adding price and volume precision parameters to the `trader` configuration file.

**Comment by nikhilsaraf** [comment]
fyi @Reidmcc
