### ISSUE TITLE
Kelp generates 'malicious activity' on external VPS providers 

### ISSUE THREAD

**Issue by cryptohodlers** [stellar/kelp#179]
After testing KELPBOT on our machines we got 2 VPS from external providers (ex: DigitalOcean) and immediately received 'service abuse' tickets due to the fact that KELPBOT generates Distributed Denial of Service Attacks (DDoS). As a result the VPS provider suspended our servers for 'malicious activity'.

• Anyone else getting this issue? Do you host bots on your own machines?
• Is it because the bot is connecting to a blockchain every minute or so (to update offers)? 
• Would you recommend a VPS provider in particular?

Cheers, Kelp-on everyone! 
#Hodlers

**Comment by Reidmcc** [comment]
Hi @cryptohodlers, I run Kelp on Amazon Web Services with no problems, so this isn't a universal problem. One thing that might cause a DDoS flag is if you have FILL_TRACKER_SLEEP_MILLIS set very low. For example, if you had `FILL_TRACKER_SLEEP_MILLIS=1` Kelp would ping your price feed source 1000 times a second, which I could see a VPS provider flagging as malicious.

**Comment by cryptohodlers** [comment]
Thank you @Reidmcc, disabled Fill Tracker (set FILL_TRACKER_SLEEP_MILLIS=0) and now works like a charm! Kelp-on! $XLM
