### ISSUE TITLE
Integrate Open Exchange Rates for FOREX currency data

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/kelp#191]
## Desired Behavior
I want to pick my forex price provider

## Impact
The desired behavior will allow me to have more choice

## Feature Suggestion
We can achieve the desired behavior by integrating https://openexchangerates.org/

**Comment by clD11** [comment]
@nikhilsaraf is this still an open issue for someone to look at?

**Comment by nikhilsaraf** [comment]
Thanks for the comment. Yes, this is still open. @clD11 you want to take a shot at this issue?

**Comment by clD11** [comment]
Hi @nikhilsaraf, thanks for the reply. I'll give it a shot. I can start looking at it tonight and ask any questions. Do you have any pointers to get me going? I see the [openexchangerates](https://openexchangerates.org/signup/free) has a forever free plan, so guess I can start integrating with that as suggested.

**Comment by nikhilsaraf** [comment]
@clD11 thats a great place to start. As reference code you could look at our “fiat” priceFeed implementation that uses the currencylayer API.
We want to create the same thing but for the open exchange rates API. Can call it “fiat-openxr”

**Comment by nikhilsaraf** [comment]
@clD11 can you add me on keybase (`@nikhilsaraf`) or Twitter (`@nikhilsaraf9`), easier to ping me there with any questions if working on this issue

**Comment by clD11** [comment]
@nikhilsaraf Sure, I am not either but can join keybase and ping you
