### ISSUE TITLE
Polishing Kelp UI for Stellar testnet after internal testing

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/kelp#210]
related to #67 

This issue is a placeholder for any issues that need to be addressed after internal testing.

Find all issues opened during the Kelpathon: https://github.com/stellar/kelp/issues?q=is%3Aissue+is%3Aopen+label%3AKelpathon

Kelpathon bugs: https://github.com/stellar/kelp/issues?q=is%3Aissue+label%3AKelpathon+label%3Abug+is%3Aopen

**Comment by msfeldstein** [comment]
menu dots jump around when opening or closing the menu
![Screenshot 2019-08-05 at 12 39 30 PM](https://user-images.githubusercontent.com/161135/62490439-2372d000-b77e-11e9-8a3e-d7bb091c4231.png)
![Screenshot 2019-08-05 at 12 39 33 PM](https://user-images.githubusercontent.com/161135/62490441-2372d000-b77e-11e9-82df-00428927f678.png)

**Comment by msfeldstein** [comment]
Give a popup that you can't edit config while the bot is running, otherwise the edit button just does nothing and you're not sure why

**Comment by msfeldstein** [comment]
Auto-save config when you press back, otherwise changes just silently disappear

**Comment by nikhilsaraf** [comment]
Hey @msfeldstein thanks for reporting these issues, these are great finds!

Could you create these as new issues? I'm using this issue here as the root for all the issues that come out of the internal testing, would be super-helpful -- and you'll get points for each of these finds!

[here's the link to easily create issues for the Kelpathon](https://github.com/stellar/kelp/issues/new?assignees=&labels=bug%2C+Kelpathon&template=sdf_internal_kelpathon_bug.md&title=)

**Comment by nikhilsaraf** [comment]
each individual item will be handled as it's own issue so don't need this overall issue.

1. auto-save may not be desired right off the bat, [separated into it's own feature request](https://github.com/stellar/kelp/issues/289).
2. waffling dots for option dropdown is already fixed [here](https://github.com/stellar/kelp/issues/243)
3. popup saying you can't edit a config when the bot is running for a better UX, [separate into it's own feature request](https://github.com/stellar/kelp/issues/290)
