### ISSUE TITLE
Dockerize Kelp

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/kelp#211]
## Desired Behavior
I should be able to start the Kelp UI as a server from docker with a simple docker command.

## Impact
Reduces the barrier to start up the Kelp UI

## Feature Specification
We can achieve the desired behavior by creating a dockerfile in `/ops` that does the following inside the docker container:
1. uses a golang image as the base
2. pulls the Kelp repo from `stellar/master`
3. runs Kelp by exposing the UI on port `8000`, using the following variables
    a. testnetHorizonURI
    b. pubnetHorizonURI
4. the kelp UI docker image itself can be started with the following configs:
    a. container can read from localhost's port `3000` to access CCXT-rest
    b. expose port `8000` from container to passed in port on localhost
    c. location of main disk of container bound to folder on localhost

**Comment by aegonet** [comment]
Hi guys, cant install bot on my mac, on linux is ok.
help me please!

thank u, Alex

**Comment by nikhilsaraf** [comment]
@aegonet  can you file a *new* issue on github regarding this and provide more details? I will take a look at it today.

**Comment by aegonet** [comment]
Thank u, i think its ok now, trying to start)

[Coinger Info](https://www.spikenow.com/?ref=spike-organic-signature&_ts=3lydg)	[3lydg]Kind regards, Coinger

On August 2, 2019 at 20:04 GMT, Nikhil Saraf <notifications@github.com> wrote:

[@aegonet](https://github.com/aegonet) can you file a new issue on github regarding this and provide more details? I will take a look at it today.

**Comment by aegonet** [comment]
Hi, how can i use more than one bot ? Thank you!

[Coinger Info](https://www.spikenow.com/?ref=spike-organic-signature&_ts=3wltt)	[3wltt]Kind regards, Coinger

On August 3, 2019 at 0:55 GMT, Nikhil Saraf <notifications@github.com> wrote:

Closed [#211](https://github.com/stellar/kelp/issues/211) via [b612070](https://github.com/stellar/kelp/commit/b61207012dd10b44220acf644703aa346834778c).
