### ISSUE TITLE
Usability issue: easy to confuse base asset / quote asset

### ISSUE THREAD

**Issue by tomquisel** [stellar/kelp#216]
It'd be nice to change the UX for buysell and maybe other strategies to clarify the correspondence between the base asset / quote asset and the numerator / denominator in the strategy. As it is, it's easy to get the quote reversed and place a terrible offer.

**Comment by nikhilsaraf** [comment]
mockup to fix this:
https://projects.invisionapp.com/share/E8SD2T46AKR#/screens/367145224_Form

Additional:
- add the issuer in the note, something like *You're valuing 1 anchorusd.com USD at 0,116 btcanchor.com BTC
- add the anchor and asset code on the numerator and denominator labels to make it clearer

**Comment by nikhilsaraf** [comment]
@brunomuler thank you for the mockup, re-assigning this issue to myself to implement the mockup
