### ISSUE TITLE
Price feed crashes if an invalid value is entered

### ISSUE THREAD

**Issue by brunomuler** [stellar/kelp#224]
## Describe the bug
While using the Kelp UI, on the Price Feed settings, if you choose "Fixed Value" and enter any invalid character (symbols, letters) the console logs the following errors:
`POST http://54.225.25.73:8015/api/v1/fetchPrice 500 (Internal Server Error)`
`Uncaught (in promise) SyntaxError: Unexpected token I in JSON at position 0`

The loader hangs and the component doesn't work unless you reload the page.

## Expected behavior
The field should accept valid characters only or validate invalid characters and display the error state and an error message.

## Frequency
Always.

## Your Environment
Using the Kelp UI.

**Comment by nikhilsaraf** [comment]
solved using the generic price feed invalid error message in the UI
