### ISSUE TITLE
Some numeric fields cannot be reset during bot creation

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/kelp#227]
## Describe the bug
Backspacing on fields like "Tick Interval" and "Maximum Randomized Tick Interval Delay" in advanced settings doesn't clear the field.

## Expected behavior
The bot should be able to clear the field entirely, and re-type the correct value. 

## Frequency
Always

## Steps To Reproduce
1. Click "Create Bot"
2. Go to "Advanced Settings"
3. Type something into "Tick Interval"
4. Try backspacing until the field is clear

**Comment by nikhilsaraf** [comment]
dupe of #218
