### ISSUE TITLE
Refreshing the /new page results in a 404 error

### ISSUE THREAD

**Issue by brunomuler** [stellar/kelp#240]
## Describe the bug
While using the Kelp UI, if you go to a new bot page ( /new page) and refresh it, an 404 error is displayed, even pressing back on the browser doesn’t work.

## Expected behavior
I think when refreshing the page should be shown just like when it loads the first time.

## Frequency
Always

**Comment by nikhilsaraf** [comment]
This already works, marking bug as closed, please feel free to reopen if not working (see attached demo) @brunomuler 

![kelp-new-screen-refresh-gif](https://user-images.githubusercontent.com/1028334/64246718-f5bea980-cf2a-11e9-89a1-93205efc946c.gif)
