### ISSUE TITLE
Upgrade dependency management system to use Go Modules

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/kelp#277]
## Desired Behavior
I want to use [Go Modules](https://github.com/golang/go/wiki/Modules) for dependency management

## Impact
The desired behavior will allow me to:
- use the **officially supported** method of dependency management in Go
- get rid of `GOPATH` requirement for the project
- remove [glide](https://github.com/Masterminds/glide) from the list of external tooling dependencies for kelp

## Feature Suggestion
We can achieve the desired behavior by upgrading the project to Go Modules.

## References
This feature exists in [stellar/go](github.com/stellar/go)

## Additional context

Some alternatives to using Go Modules that would achieve the same result are:
- glide (existing)
- dep
- gb (outdated?)

I have not completed a full evaluation of which approach is best, but there are enough requests from the community to move away from glide, Go Modules is officially supported as the dependency management system in Golang as off Go version 1.11 and [stellar/go](github.com/stellar/go) uses it as well.

See Specifications section below for details on our requirements

## Specification
One requirement for the solution we converge on is the ability to lock `hashes` in addition to `version tags` for our dependencies. Glide allows this and our end solution must as well. This ensures 100% reproducibility in our builds on the same platform.

**Comment by clD11** [comment]
I can pick this one up

**Comment by nikhilsaraf** [comment]
Closed by https://github.com/stellar/kelp/commit/ba17509ade15afbc8c4363ab6ae0a0dd8db08567
