### ISSUE TITLE
[1] panic: runtime error: index out of range

### ISSUE THREAD

**Issue by SujithStellargoldcoin** [stellar/kelp#309]
I am new to Kelp and i tried to configure Kelp for sdex(stellar term) and I have configured my buysell.cfg and trader.cfg. However, the bot started to run but it shows the above error. I didn't change the sell indexes for my coin

**Comment by nikhilsaraf** [comment]
@SujithStellargoldcoin can you attach the log file please?

**Comment by nikhilsaraf** [comment]
@SujithStellargoldcoin closing this issue for now, if it's still not working for you then please feel free to reopen.
