### ISSUE TITLE
Unable to find proper guide to configure bot for my exchange software 

### ISSUE THREAD

**Issue by taalhach** [stellar/kelp#337]
I have implemented api.Exchange interface for an exchange software but after that i don't know how to configure and run the bot for market making on exchange software.
I have gone through sample_trade.cfg and sample_buysell.cfg but i can't understand how to configure it for my exchange software.
I need to know which cfg parameters i need to set to run bot?

**Comment by taalhach** [comment]
@nikhilsaraf i need your input here please help me

**Comment by nikhilsaraf** [comment]
@taalhach You can follow the example of `krakenExchange.go` for the implementation of `api.Exchange`.

Once you have an implementation of `api.Exchange` then you can make an addition to `plugins/factory.go#loadExchanges()`.

Once that's done then you can use your exchange integration in the same way that you use the `kraken` exchange.

**Comment by taalhach** [comment]
thanks @nikhilsaraf i did everything and configurations were pretty confusing but its working somehow :p

**Comment by nikhilsaraf** [comment]
ok great. @taalhach, if this is an exchange with a lot of users then would you like to contribute your change back upstream?

**Comment by taalhach** [comment]
our exchange will go live in some months and we have some work to do with our APIs and authentication via secret keys after that its done then i will submit PR.
Kelp is super easy to integrate and thank you for that

**Comment by taalhach** [comment]
i ran buysell and sell strategy it worked fine but now i am running balanced strategy with same trader config it throws error like 
```
2020/01/15 16:07:07 using CCXT-rest URL: http://localhost:3000
2020/01/15 16:07:07 ccxt-rest is not running at http://localhost:3000 so we cannot include those exchanges: could not execute http request: Get http://localhost:3000/exchanges: dial tcp 127.0.0.1:3000: connect: connection refused
2020/01/15 16:07:07 Using network passphrase: Test SDF Network ; September 2015
2020/01/15 16:07:07 No Source Account Set
2020/01/15 16:07:07 Making strategy: buysell
2020/01/15 16:07:07 Unknown fields: [SPREAD MIN_AMOUNT_SPREAD MAX_AMOUNT_SPREAD MAX_LEVELS LEVEL_DENSITY ENSURE_FIRST_N_LEVELS MIN_AMOUNT_CARRYOVER_SPREAD MAX_AMOUNT_CARRYOVER_SPREAD CARRYOVER_INCLUSION_PROBABILITY VIRTUAL_BALANCE_BASE VIRTUAL_BALANCE_QUOTE]
2020/01/15 16:07:07 
2020/01/15 16:07:07 error: could not parse the config file '/home/resilient/go/src/github.com/stellar/kelp/examples/configs/trader/sample_balanced.cfg'. Check that the correct type of file was passed in.
```
my question is do i need to run ccxt server is it necessary or what ?

**Comment by nikhilsaraf** [comment]
@taalhach that sounds great. closing this issue for now since it's resolved.

it seems like you are trying to run the `buysell` strategy but you are passing the config for a `balanced` strategy. check the input arguments you are passing to the binary. the `--strategy` param should have a value of `balanced`.

**Comment by waqas10075** [comment]
im trying to run kelp bot , but my ccxt is not connecting to localhost:3000
![Screenshot from 2021-08-23 16-28-07](https://user-images.githubusercontent.com/7556774/130440133-ed95f6c6-9b74-4862-95b7-b09c2bdb6a96.png)

**Comment by waqas10075** [comment]
in trying to configure kelp bot, but it is not connecting to my localhost 
![Screenshot from 2021-08-23 16-28-07](https://user-images.githubusercontent.com/7556774/130442052-0b6098e8-13e8-4fce-8341-ece3f79e7175.png)
