### ISSUE TITLE
[3] Upgrade horizonclient to v2 to fix horizon v1 API change in load offers

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/kelp#360]
## Describe the bug
This is the error message I am seeing on the test network: `unable to load existing offers: Can't load offers: json: cannot unmarshal string into Go struct field Offer._embedded.records.id of type int64`.

This needs to work for older versions of horizon too.

## Expected behavior
I think the correct behavior in this situation is for the bot to work

## Frequency
The frequency is: Always on horizon v1

**Comment by ire-and-curses** [comment]
Surprised to see this because we made the types backwards compatible in the Go SDK. Could you check that you're using the latest version of the SDK? cc @abuiles

**Comment by abuiles** [comment]
@nikhilsaraf as Eric point out, version 2.0 of horizonclient offers backwards compatibility support for this, which version are you using?

**Comment by nikhilsaraf** [comment]
Kelp's [glide.yaml](https://github.com/stellar/kelp/blob/12eccd2a566e68a707e5777d9b2759c239f10cb5/glide.yaml#L12) shows that it is [currently using v1.3](https://github.com/stellar/go/blob/a599ed95b928a7bdcee21cee4999efd05e43c2df/clients/horizonclient/version.go) -- I'll upgrade to v2
