### ISSUE TITLE
Can't run version 1.8.0 on arm6

### ISSUE THREAD

**Issue by joaofrp** [stellar/kelp#369]
## Describe the bug
The bot crashes when starting since updating to v1.8.0 on arm6.

## Expected behavior
The bot should run the complete cycle.

## Frequency
Always

## Steps To Reproduce
Run version 1.8.0 on a arm6 processor.

## Your Environment
cli version: master:v1.8.0
 gui version: v0.0.1-alpha
 git branch: master
 git hash: 53691b9813183d96ac5bb8f18e67f2c83d8d2a4f
 build date: 20200211T223323Z
 env: release
 GOOS: linux
 GOARCH: arm

## Attachments
The bot returns this error: _"unable to load existing offers: Can't load offers: json: invalid use of ,string struct tag, trying to unmarshal unquoted value into int64"_

Then returns _"updated lastCursor value to"_ every second or so until the next cycle.

**Comment by nikhilsaraf** [comment]
@joaofrp
thanks for filing this issue!
I'm working on a fix right now and should release v1.8.1 soon.
