### ISSUE TITLE
[3] Kelp GUI: App won't open on Windows platform

### ISSUE THREAD

**Issue by tyvdh** [stellar/kelp#390]
## Describe the bug
Application won't open on Windows. Simple as that. On Mac I had to move the app into the "Applications" directory so maybe there's some similar logic here but I'm unsure.

## Expected behavior
App should open when installed and icon is clicked.

## Frequency
Always.

## Steps To Reproduce
Install app for windows, decompress zip file, click icon, nothing...

**Comment by nikhilsaraf** [comment]
2 points because dealing with windows is a pain

**Comment by nikhilsaraf** [comment]
we've made this process easier by adding installation instructions and various scripts to help get set up. If we need more work on this then I will open a new issue. https://github.com/stellar/kelp/issues/674
