### ISSUE TITLE
Index out of range when getting prices from sdex

### ISSUE THREAD

**Issue by joaofrp** [stellar/kelp#416]
## Describe the bug
Getting error "index out of range" when the bot gets the price feed of two tokens on the sdex

## Frequency
Always

## Steps To Reproduce
Set the bot to get a feed from the sdex, for example:

DATA_TYPE_A="sdex"
DATA_FEED_A_URL="BTC:GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF/BTC:GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5"
DATA_TYPE_B="fixed"
DATA_FEED_B_URL="1.0"

## Your Environment
cli version: master:v1.8.1
gui version: v0.0.1-alpha
git branch: master
git hash: 90e31022e46f5585a81f6890e6a1d4747455673f
build date: 20200217T212830Z
env: release
GOOS: linux
GOARCH: arm

**Comment by nikhilsaraf** [comment]
Had missed this issuer earlier. Are you still getting this issue? If so, can you please send me the log file (or upload to the issue here?)

**Comment by joaofrp** [comment]
Yes, I'm still getting this issue in version 1.9.0. Here is the log file:

[log_BTC_GCNSGHUCG5VMGLT5RIYYZSO7VQULQKAJ62QA33DBC5PPBSO57LFWVV6P_BTC_GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5_20200512T220051WEST.log](https://github.com/stellar/kelp/files/4618467/log_BTC_GCNSGHUCG5VMGLT5RIYYZSO7VQULQKAJ62QA33DBC5PPBSO57LFWVV6P_BTC_GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5_20200512T220051WEST.log)

**Comment by nikhilsaraf** [comment]
@joaofrp The log files does not show the `index out of range` error. Can you give me a log file that shows that error?

Separately, I noticed that your log file shows that you don't have any balance of one of quote BTC asset.  Can you fix that and see if it resolved the issue?

> 2020/05/12 22:00:57  (base) assetA=BTC:GCNSGHUCG5VMGLT5RIYYZSO7VQULQKAJ62QA33DBC5PPBSO57LFWVV6P, maxA=0.08237120, trustA=922337203685.47753906
> 2020/05/12 22:00:57 (quote) assetB=BTC:GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5, _**maxB=0.00000000**_, trustB=900000000000.00000000
> ...
> ...
> 2020/05/12 22:00:59 no capacity to place sell orders (nothingToSell = true, lineFull = false)

**Comment by joaofrp** [comment]
@nikhilsaraf Here is a log file that shows the error:

[log_BTC_GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF_BTC_GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5_20200513T094151WEST.log](https://github.com/stellar/kelp/files/4620763/log_BTC_GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF_BTC_GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5_20200513T094151WEST.log)

Now I have a non zero balance in both assets and the error still happened.

**Comment by nikhilsaraf** [comment]
@joaofrp fixed the issue. Are you running from the source code, in which case you can pull from master to get the fix.
Or are you running from a pre-compiled binary, in which case I can upload a binary for your platform here.

**Comment by joaofrp** [comment]
@nikhilsaraf Thank you for your work! I'll pull from master.
