### ISSUE TITLE
Kelp GUI - Can't select fiat currency when creating a new bot 

### ISSUE THREAD

**Issue by HATTER-MU** [stellar/kelp#418]
When creating a new buy/sell bot, with a fiat (currency layer) data feed.

The drop down menus don't let you select any currency other than AED. The first currency on the list.

We've tried numerous browsers, machines etc, but the problem persists.

See video [over here](https://drive.google.com/file/d/1kMUct7__vMzMEIduoiTORgzkuPZvby-G/view?usp=sharing) .

**Comment by nikhilsaraf** [comment]
@HATTER-MU can you try 3 different currencies (any). I believe the price will change in the bot internally but the display of the dropdown is faulty and will not show the update, i.e. it will register correctly with the bot and when you run it it will use the desired fiat value selected.

Please try this out and let me know if it works? A fix is on the way.

**Comment by nikhilsaraf** [comment]
@HATTER-MU you can find the bugfix in the [latest nightly release I just uploaded](https://github.com/stellar/kelp/releases/tag/nightly-33ab2afe). Hope this helps! 👍
