### ISSUE TITLE
TargetPrice is 0 Error Balanced strategy

### ISSUE THREAD

**Issue by BouweCeunen** [stellar/kelp#425]
## Describe the bug
`error in selling sub-strategy: unable to create preceding offers: could not compute targets: targetPrice is 0`

## Expected behavior
I think the correct behavior in this situation is for the bot to trade XLM for USD and vice versa.

## Frequency
The frequency is: always.

## Steps To Reproduce
It started trading and has traded to a balance of 0 USD. It generates this error now.

## Possible Solution
/

## Your Environment
  cli version: (no:v1.9.0
  gui version: v1.0.0-rc1
  git branch: (no
  git hash: ab3333ed871e81124b59d053b60a5856aecc5f41
  build date: 20200514T081355Z
  env: dev
  GOOS: linux
  GOARCH: amd64

## Context
I am unable to trade with Kelp because of this bug.

## Attachments
/

**Comment by nikhilsaraf** [comment]
@BouweCeunen could you please upload the full log file to help understand the root cause of the issue?

**Comment by BouweCeunen** [comment]
It goes on like this:

```2020/05/21 17:16:20 sleeping for 59.735955053s...
2020/05/21 17:16:21 updated lastCursor value to 127804311034941441-2
2020/05/21 17:16:31 updated lastCursor value to 127804311034941441-2
2020/05/21 17:16:41 updated lastCursor value to 127804311034941441-2
2020/05/21 17:16:51 updated lastCursor value to 127804311034941441-2
2020/05/21 17:17:01 updated lastCursor value to 127804311034941441-2
2020/05/21 17:17:11 updated lastCursor value to 127804311034941441-2
2020/05/21 17:17:20 intervalTimeController tickInterval=1m0s, shouldUpdate=true, elapsedSinceUpdate=1m0.079081117s
2020/05/21 17:17:20  (base) assetA=native, maxA=972.84108190, trustA=math.MaxFloat64
2020/05/21 17:17:20 (quote) assetB=USD:GDUKMGUGDZQK6YHYA5Z6AY2G4XDSZPSZ3SW5UN3ARVMO6QSRDWP5YLEX, maxB=0.00000000, trustB=922337203685.47753906
2020/05/21 17:17:20 orderConstraints for trading pair XLM/USD: OrderConstraints[PricePrecision: 7, VolumePrecision: 7, MinBaseVolume: 0.0000001, MinQuoteVolume: <nil>]
2020/05/21 17:17:20 liabilities after resetting
2020/05/21 17:17:20 asset=base  , balance=972.84108190, trust=math.MaxFloat64, minAccountBal=21.50000000, buyingLiabilities=0.00000000, sellingLiabilities=0.00000000
2020/05/21 17:17:20 asset=quote , balance=0.00000000, trust=922337203685.47753906, minAccountBal=0.00000000, buyingLiabilities=0.00000000, sellingLiabilities=0.00000000
2020/05/21 17:17:20 no capacity to place sell orders (nothingToSell = true, lineFull = false)
2020/05/21 17:17:20 no offers were taken, leave levels as they are
2020/05/21 17:17:20 created 0 operations to prune excess offers
2020/05/21 17:17:20 liabilities after resetting
2020/05/21 17:17:20 asset=base  , balance=972.84108190, trust=math.MaxFloat64, minAccountBal=21.50000000, buyingLiabilities=0.00000000, sellingLiabilities=0.00000000
2020/05/21 17:17:20 asset=quote , balance=0.00000000, trust=922337203685.47753906, minAccountBal=0.00000000, buyingLiabilities=0.00000000, sellingLiabilities=0.00000000
2020/05/21 17:17:20 buy , done creating preceding offers (numLevelsConsumed=0, hitCapacityLimit=false, numOps=0, newTopOfferPrice=<nil>)
2020/05/21 17:17:20 liabilities at the end of a call to UpdateWithOps
2020/05/21 17:17:20 asset=base  , balance=972.84108190, trust=math.MaxFloat64, minAccountBal=21.50000000, buyingLiabilities=0.00000000, sellingLiabilities=0.00000000
2020/05/21 17:17:20 asset=quote , balance=0.00000000, trust=922337203685.47753906, minAccountBal=0.00000000, buyingLiabilities=0.00000000, sellingLiabilities=0.00000000
2020/05/21 17:17:20 error in selling sub-strategy: unable to create preceding offers: could not compute targets: targetPrice is 0
2020/05/21 17:17:20 liabilities (force recomputed) after encountering an error after a call to UpdateWithOps
2020/05/21 17:17:20 asset=base  , balance=972.84108190, trust=math.MaxFloat64, minAccountBal=21.50000000, buyingLiabilities=0.00000000, sellingLiabilities=0.00000000
2020/05/21 17:17:20 asset=quote , balance=0.00000000, trust=922337203685.47753906, minAccountBal=0.00000000, buyingLiabilities=0.00000000, sellingLiabilities=0.00000000
2020/05/21 17:17:20 deleting all offers, num. continuous update cycles with errors (including this one): 11; (deleteCyclesThreshold to be exceeded=0)
2020/05/21 17:17:20 created 0 operations to delete offers

**Comment by BouweCeunen** [comment]
[logs-from-kelp-in-kelp-5d65d67b58-cjmhx.txt](https://github.com/stellar/kelp/files/4663883/logs-from-kelp-in-kelp-5d65d67b58-cjmhx.txt)

**Comment by BouweCeunen** [comment]
Can this be caused by this first order in the order book? 
![image](https://user-images.githubusercontent.com/5576686/82590781-95e25e80-9b9e-11ea-90d9-5b5cc6926c72.png)

**Comment by BouweCeunen** [comment]
If my USD balance is not 0, kelp resumes trading.

**Comment by BouweCeunen** [comment]
I think it's related to https://github.com/stellar/kelp/issues/306

**Comment by BouweCeunen** [comment]
The bot just ran for a few hours/days, did not do anything special. I did a workaround by restarting it every x minutes, this is working but not really clean. Not sure how I can be of further help.

**Comment by nikhilsaraf** [comment]
@BouweCeunen the full log file would help to give me more info about where the bot messed up. This should be the log file where your bot crashes for the first time.
Could you please share that? You can send it to me via keybase if you prefer sending it privately (keybase: nikhilsaraf)

For now I'd suggest adding a larger USD balance to the account based on the specific requirements of the strategy (correct ratio based on desired price etc.)

**Comment by BouweCeunen** [comment]
I'm afraid I don't have the full log file anymore, I restarted it and changed configuration and now it does not occur anymore. I think we can close this and progress on the other issue #306.
