### ISSUE TITLE
Kelp GUI on windows not selecting right currency

### ISSUE THREAD

**Issue by layinka** [stellar/kelp#426]
// see a sample bug report here: https://github.com/stellar/kelp/issues/1

## Describe the bug
// A succinct description of the buggy behavior.
// This section includes **what** the bot is doing and **why** you think it is incorrect.

The bot does not update the selected Currency when a Fiat(currencyLayer) feed is selected. It uses the selected currency for its calculation but the first currency is shown on the dropdown, so the user is not sure if his selection was chosen

## Expected behavior
// A succinct description of **what you expected to happen**.

I think the correct behavior in this situation is for the bot to update the selected fiat currency

## Frequency
// **How often** does this happen?
//     Unpredictable = it's hard to predict when it will happen
//     Sometimes = it happens every now and then but there's no pattern to it
//     Always = it always happens consistently at the same point

The frequency is: Always

## Steps To Reproduce
// A concise description of the **steps to reproduce the buggy behavior** along with screenshots wherever applicable:

Here are the steps to reproduce the issue (see attachments in section below):
1. Select Fiat(CurrencyLayer) under Numerator or Denominator in price strategy
2. Select any currency apart from AED, 
3. You will see currency is changed back to AED
...

## Your Environment
// Run `kelp version` to get the version and build information and paste it here
//   cli version: v1.0.0-rc1
//   gui version: v0.0.1
//   git hash: 1bcc4e9fa4012867a549472dbdf61cb008041305
//   build date: 20180813T013016Z
//   GOOS: linux
//   GOARCH: amd64

Kelp GUI on windows - WSL - Ubuntu 18
Cli version:  v1.0.0-rc1 (master:v1.9.0)
gui version:  kelp_ui_v1.0.0-rc1__cli_v1.9.0-windows-amd64

...

## Context
// A succinct description of how has this bug has **affected you** or prevented you from accomplishing what you wanted.

I am unable to know the currency being used in calculation because of this bug.

## Attachments
// Attach any relevant configuration files, logs, tx hashes, etc. here.
No Attachment

**Comment by nikhilsaraf** [comment]
Thank you for reporting this. It has already been [fixed](https://github.com/stellar/kelp/issues/418) and released in the nightly build.

You can download it from here: https://github.com/stellar/kelp/releases/tag/nightly-33ab2afe

closing this issue but if it's still unresolved please feel free to reopen.
