### ISSUE TITLE
electron-windows-amd64-v4.0.1.zip is not a valid zip file

### ISSUE THREAD

**Issue by g8d3** [stellar/kelp#565]
## Describe the bug

I can not run app on windows 10.

## Expected behavior

To run the app.

## Steps To Reproduce

1. Download binaries from:

https://github.com/stellar/kelp/releases/download/v1.10.0/kelp-v1.10.0-windows-amd64.tar

2. Extract tar file to a folder
3. cd into that folder using cmd
4. run `./kelp.exe`

## Your Environment

```
  cli version: master:v1.10.0
  gui version: v1.0.0-rc1
  git branch: master
  git hash: b4ea3fed07ae26831c9b85bbc80c6e5dfe268c47
  build date: 20201022T184632Z
  env: release
  GOOS: windows
  GOARCH: amd64
```

## Attachments

[Logs](https://gist.github.com/g8d3/75f10784b0e824108de4d2c83231081d).

**Comment by nikhilsaraf** [comment]
Can you try running this:
kelp.exe -h

If you are looking to use the GUI, please try downloading from the [latest nightly build of the GUI](https://github.com/stellar/kelp/releases/tag/nightly-33ab2afe)

**Comment by nikhilsaraf** [comment]
@g8d3 you need to run using the `.bat` file on windows.
we are fixing this so that you can run directly using the `kelp.exe` binary in ([this issue](https://github.com/stellar/kelp/issues/568))
