### ISSUE TITLE
Sign binaries

### ISSUE THREAD

**Issue by antb321** [stellar/kelp#566]
It would be nice to provide signitures for the binaries so when we download them we can verify they are valid.

**Comment by nikhilsaraf** [comment]
@antb123 we are currently providing MD5 hashes for individual releases such as [v1.10.0](https://github.com/stellar/kelp/releases/tag/v1.10.0) -- see `Checksum` section.

Are you referring to "verified released binaries" so it's verified that it's uploaded by SDF vs someone malicious?

**Comment by antb123** [comment]
i didn't see the checksum - I was looking for gpg but md5 is fine.. thanks!

**Comment by nikhilsaraf** [comment]
Great, thanks! Closing this out
