### ISSUE TITLE
[1] add GOARM versions in metrics, or remove TODO and explain in comment why its missing

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/kelp#567]

**Comment by debnil** [comment]
Currently, this is missing because the `runtime` package doesn't expose `GOARM`, and it's not clear there is a standard way to do this using Go packages.

We can potentially do this through defining and exporting a `GOARM` variable from the build script. Should we follow this path?

**Comment by nikhilsaraf** [comment]
yes, build script makes sense. we will need to be careful since this will be the first case of an ldflags parameter that is not global for the entire build script and needs to be injected correctly for each and every build. not sure if you can have multiple -ldflags cli options when building but if you can then that's perfect. if not we will need to maybe do some string manipulation to get it working correctly

**Comment by debnil** [comment]
I'm not sure how we inject this correctly, and I don't think you can have multiple -ldflags options on build.

But, even if we can do those things, I'm not sure we can reliably define `GOARM` for users not using the hand-rolled binaries. Currently, `GOARM` is only defined on deploy, and it uses specific choices of `GOARM` that are defined in `PLATFORM_ARGS`. It isn't done earlier in the script when the `cmd` package variables are exported. So, I don't know if this export is possible. Thoughts?

**Comment by nikhilsaraf** [comment]
@debnil can we do something where we create a temporary `LDFLAGS_WITH_GOARM` variable that is "LDFLAGS + GOARM" ([here](https://github.com/stellar/kelp/blob/master/scripts/build.sh#L329))?
