### ISSUE TITLE
[ad-hoc] botName 'Eurcny': horizon error: "Rate Limit Exceeded" - check horizon.Error.Problem for more information

### ISSUE THREAD

**Issue by tundak** [stellar/kelp#575]
Using kelp GUI with` v1.10.0` and we are running approx 25 bots on it. Also we have setup own horizon with rate limit `75000` Bot reporting issue `horizon error: "Rate Limit Exceeded" - check horizon.Error.Problem for more information`

**Comment by nikhilsaraf** [comment]
@tundak
1. are you running this on production or the test network?
1. have you tried increasing the rate limit of your horizon server? (or reducing the interval time of each bot update)

**Comment by tundak** [comment]
1. testnet
2. seems good with higher horizon rate limit.
