### ISSUE TITLE
Refactor volume filter function

### ISSUE THREAD

**Issue by debnil** [stellar/kelp#604]
The `volumeFilterFn` within `plugins/volumeFilter.go` can be significantly streamlined. The below flowchart outlines its logical flow to help guide a refactor.

![Volume filter function flowchart](https://user-images.githubusercontent.com/1740974/101227686-9aa7c500-364d-11eb-940d-c09201696085.png)

**Comment by debnil** [comment]
When looking at the above flowchart, we’re basically trying to answer: when should either the base or quote asset keep being sold?
1. If the relevant cap is nil. Then, we return the operation with the same amount.
2. The projected amount sold is within the cap’s value. Then, we return the operation with the same amount.
3. If the mode is exact and there’s still remaining capacity. Then, we update the amount on the operation and return it.

If one of the above conditions is not met for exactly one asset, we return no operation.

**Comment by nikhilsaraf** [comment]
Flowchart is awesome, well done! 💯

**Comment by debnil** [comment]
This reworked/simplified version of the above flowchart converts a buying op to a selling op and formats a base cap as a quote cap. This simplifies it down to a single workflow.

![Reworked flowchart](https://user-images.githubusercontent.com/1740974/102139058-2cfc5580-3e12-11eb-939c-fe142acc9dfc.png)

**Comment by nikhilsaraf** [comment]
1. we probably want to update the op amount only in the case where there is remaining capacity (bottom right of second flowchart). In the case where there is no remaining capacity we should discard the op (i.e. don't keep selling quote).

2. I'm not sure if we can convert a base cap to a quote cap. I think the more appropriate thing to do is to "select otb, tbb, cap from base part of inputs" or from the quote part of inputs. I'm thinking that the common format we select will not have any idea of "base" or "quote" but only has an understanding of otb, tbb, cap, and offerAmount. Any conversions/transformations/selections before that should provide this invariant. What do you think?

3. we probably need logic (box) to convert sell offers back to buy offers. What is the best place to put this? based on the Tip below do we even need this?

4. we also need a box to represent where and when we will update the TBB values. should we do this before converting back to a buy op or before? (i.e. what is the unit of accounting here)

------

Tip:
- a "sell base" limit is a limit on the amount of base asset that is sold as a result of selling the base asset.
- a "sell quote" limit is a limit on the amount of base asset that is sold denominated in the quote asset, i.e. the amount of quote asset that is purchased as a result of selling the base asset.
- a "buy base" limit is a limit on the amount of base asset that is purchased as a result of buying the base asset.
- a "buy quote" limit is a limit on the amount of base asset bought denominated in the quote asset, i.e. the amount of quote asset that is sold as a result of purchasing the base asset.

This raises the question of whether a buy operation (buying base and selling quote) will be constrained by a "sell quote" filter. I don't think so. I think it should only be affected by "buy" filters. similarly for sell operations.

(we should document this correctly in the config file and review tests in dailyVolumeByDate, added as a separate issue here so we don't forget: https://github.com/stellar/kelp/issues/623)

This may require us to have logic at the top of the flowchart where we do a passthrough if the filter type (buy/sell) is different from the offer type (buy/sell).

**Comment by debnil** [comment]
<img width="713" alt="Revised flowchart for volume filter fn" src="https://user-images.githubusercontent.com/1740974/102261007-ed8f4100-3ec5-11eb-882f-baac36825643.png">


Got it, the above is helpful.
1. That was my mistake, edited in new flowchart.
2. Agreed, edited.
3. I don't think we need this based on the tip. I've edited the flowchart to have the passthrough logic.
4. I've added a box for this, we don't need conversion given the tip.

**Comment by nikhilsaraf** [comment]
Good call on the conversion back to buy ops, doesn’t seem like it’s required.

I think we can get to the desired solution with the above proposal and can’t think of anything in particular that sticks out. Thanks for putting this together. Let’s get this converted to code! 🎉

**Comment by nikhilsaraf** [comment]
I believe this is fully completed (unless I've missed something), reflecting by closing issue.
