### ISSUE TITLE
Kelp exits unexpectedly after "(async) error: no result codes from horizon: result_codes not populated"

### ISSUE THREAD

**Issue by MojoMoe** [stellar/kelp#638]
Hi. I have been testing Kelp on Ubuntu 20.04 since yesterday and it exits unexpectedly. Please see the below terminal output. Not sure if you need any more info. The behaviour was seen with sample_balanced.cfg and also when I updated the same file with my test parameters. Any idea how I can fix this or is it a known bug?

2020/12/29 11:54:28 liabilities at the end of a call to UpdateWithOps
2020/12/29 11:54:28 asset=base  , balance=106.42852440, trust=math.MaxFloat64, minAcco                           untBal=51.50000000, buyingLiabilities=8.24873671, sellingLiabilities=7.53476210
2020/12/29 11:54:28 asset=quote , balance=14.42702550, trust=922337203685.47753906, mi                           nAccountBal=0.01442703, buyingLiabilities=1.14177959, sellingLiabilities=1.03791070
2020/12/29 11:54:28 orderConstraintsFilter: dropped 0, kept 0 ops from original 0 ops, len(filteredOps) = 0
2020/12/29 11:54:28 created 0 operations to update existing offers
2020/12/29 11:54:28 ------------------------------------------------------------------                           ----------------------------------
2020/12/29 11:54:28 sleeping for 1m58.180860383s...
2020/12/29 11:55:13 there were no trades, leaving lastCursor value as 143031529174114305-2
2020/12/29 11:56:27 intervalTimeController tickInterval=2m0s, shouldUpdate=true, elaps              edSinceUpdate=2m0.000310042s
2020/12/29 11:56:42 unable to get balances1: error fetching base balance: error: unable to load account to fetch balance: Get https://horizon.stellar.org/accounts/GBG6JDIPPZSXSR4L3M4FTV6PFV5QDFQIDYV3OT3Y*******************: dial tcp: lookup horizon.stellar.org  on 127.0.0.53:53: read udp 127.0.0.1:56962->127.0.0.53:53: i/o timeout
2020/12/29 11:56:42 deleting all offers, num. continuous update cycles with errors (including this one): 1; (deleteCyclesThreshold to be exceeded=0)
2020/12/29 11:56:42 created 60 operations to delete offers
2020/12/29 11:56:42 lastFee <= maxOpFeeStroops; using last_ledger_base_fee of 100 stroops (maxOpFeeStroops = 5000)
**2020/12/29 11:56:42 tx XDR: MANY LINES OF STRINGS (HASH???)**
2020/12/29 11:56:42 submitting tx XDR to network (async)
2020/12/29 11:56:42 started thread to crash bot in 1 minute as a fallback (to respect deleteCyclesThreshold)
2020/12/29 11:56:42 metric - successfully sent event metric of type 'delete_offers'
2020/12/29 11:57:13 (async) error: no result codes from horizon: result_codes not populated
2020/12/29 11:57:13 (async) ...deleted 60 offers, exiting (asyncCallback: hash=, e=result_codes not populated)

**Comment by nikhilsaraf** [comment]
@MojoMoe thank you for filing. I think this is likely caused from a failure that occurred above the section pasted above.
Can you upload your log file please?

**Comment by MojoMoe** [comment]
> @MojoMoe thank you for filing. I think this is likely caused from a failure that occurred above the section pasted above.
> Can you upload your log file please?

I have updated the terminal output above. Couldn't find anything in 'journalctl' logs for that time when it failed. Does Kelp generate any logs stored somewhere? Thank you for the quick response btw and for the fab work you are doing with Kelp :)

**Comment by MojoMoe** [comment]
This just happened, it looks like it could be related to the other error above perhaps:


2020/12/29 15:58:29 liabilities at the end of a call to UpdateWithOps
2020/12/29 15:58:29 asset=base  , balance=108.05926320, trust=math.MaxFloat64, minAccountBal=50.50000000, buyingLiabilities=8.40172236, sellingLiabilities=8.74228430
2020/12/29 15:58:29 asset=quote , balance=14.21758370, trust=922337203685.47753906, minAccountBal=0.01421758, buyingLiabilities=1.11270607, sellingLiabilities=1.01993540
2020/12/29 15:58:29 orderConstraintsFilter: selling, baseAmount=0.25110210, quoteAmount=0.03808712, keep = true
2020/12/29 15:58:29 orderConstraintsFilter: selling, baseAmount=0.25047630, quoteAmount=0.03818226, keep = true
2020/12/29 15:58:29 orderConstraintsFilter: dropped 0, kept 2 ops from original 2 ops, len(filteredOps) = 2
2020/12/29 15:58:29 created 2 operations to update existing offers
2020/12/29 15:58:29 lastFee <= maxOpFeeStroops; using last_ledger_base_fee of 100 stroops (maxOpFeeStroops = 5000)
**2020/12/29 15:58:29 tx XDR:  ****LONG STRING*******
2020/12/29 15:58:29 submitting tx XDR to network (async)
2020/12/29 15:59:00 (async) error: no result codes from horizon: result_codes not populated
2020/12/29 15:59:00 (async) deleting all offers, num. continuous update cycles with errors (including this one): 1; (deleteCyclesThreshold to be exceeded=0)
2020/12/29 15:59:00 (async) created 58 operations to delete offers
2020/12/29 15:59:00 maxFeeInt64 > maxOpFeeStroops; using maxOpFeeStroops of 5000 stroops (percentile=90, maxFee=65076 stroops)
**2020/12/29 15:59:00 tx XDR: ****VERY LONG STRING*******
2020/12/29 15:59:00 submitting tx XDR to network (async)
2020/12/29 15:59:00 (async) started thread to crash bot in 1 minute as a fallback (to respect deleteCyclesThreshold)
2020/12/29 15:59:00 metric - successfully sent event metric of type 'delete_offers'
2020/12/29 15:59:10 (async) error: tx_bad_seq, setting flag to reload seq number
2020/12/29 15:59:10 (async) error: result code details: tx code = tx_bad_seq , opcodes = []
2020/12/29 15:59:10 (async) ...deleted 58 offers, exiting (asyncCallback: hash=, e=horizon error: "Transaction Failed" - check horizon.Error.Problem for more information)

**Comment by nikhilsaraf** [comment]
@MojoMoe the failure in your first log output above shows the following lines, which indicates that there was an inconsistent network:

```
unable to get balances1: error fetching base balance: error: unable to load account to fetch balance: Get https://horizon.stellar.org/accounts/GBG6JDIPPZSXSR4L3M4FTV6PFV5QDFQIDYV3OT3Y*******************: dial tcp: lookup horizon.stellar.org on 127.0.0.53:53: read udp 127.0.0.1:56962->127.0.0.53:53: i/o timeout
2020/12/29 11:56:42 deleting all offers, num. continuous update cycles with errors (including this one): 1; (deleteCyclesThreshold to be exceeded=0)
```

You can add some "resiliency" to Kelp by setting the `DELETE_CYCLES_THRESHOLD` config param in the trader.cfg file. This defaults to 0 which indicates to Kelp that it should fail on the first error (such as network error or any other error). Experiment with this parameter to see what you're comfortable with. The comment against this field in the `sample_trader.cfg` file does a better job of explaining the full usage. I can elaborate on that explanation if needed.

-----

Your second error was unrelated to the first error but should be overcome by setting the `DELETE_CYCLES_THRESHOLD` field.

There was also a `tx_bad_seq` error in your second log, which generally means that the account is being used by you somewhere else. It's generally a good practice to use the `SOURCE_ACCOUNT` feature in Kelp so you can use channels to consume the seq number if you want to use that account in other places.

Let me know if this works for you and I can close out the issue accordingly.

**Comment by nikhilsaraf** [comment]
Thank you! Kelp outputs the log to the terminal, but you can use the `- l` (small L) flag with a prefix to additionally have the logs send to a specific file prefix. This will append the asset code and issuers along with a timestamp. Example:
```
./kelp -c ./sample_trader.cfg -s buysell -f ./sample_buysell.cfg -l logs/buysell
```

----

You can get a full list of options by using the `-h` command such as:
```
./kelp -h
./kelp trade -h
```
------

If you are using the `buysell` trading template then you can try to use the Kelp GUI by running this:
```
// linux or mac
./kelp server

// windows
./kelp server --no-electron
```

**Comment by MojoMoe** [comment]
I knew there must have been a config I was getting wrong somewhere, thank you for looking at this for me I appreciate that.  I do have a source account set up in trader.cfg, however when I check the account I don't see any transactions (fees) being logged on it so I am not sure why that is happening. I am using the balancing trade strategy if that makes any difference.
