### ISSUE TITLE
Compile or use October's 1.10?

### ISSUE THREAD

**Issue by BenRacicot** [stellar/kelp#640]
Hello! Just wanted to ask if 1.10 (from October) is still relevant? 
There seems to be a lot of commits since then, is 1.10 missing anything critical?

Perhaps I should officially ask for the latest binaries in a new release version :)

Thanks for your work on Kelp!

**Comment by nikhilsaraf** [comment]
Hi Ben, thank you for trying Kelp!

**v1.10.0 is still relevant and is the most stable release.**

There's not enough changes to justify a new binary version so I haven't released yet. I will be adding some more changes in the coming month and will include everything since October into this new release (v1.11.0) which will happen most likely in February.

If you are looking to use the latest features as they are merged, you can try [compiling from source](https://github.com/stellar/kelp#compile-from-source).

Please feel free to close this issue if you feel that it is resolved. If you have alternative suggestions that would make it easier for you to get started with Kelp then I'm all ears :)

**Comment by BenRacicot** [comment]
Hi @nikhilsaraf ,

Understood. FWIW I'd like to explain my experiences setting up GoLang (I'm an Engineer focused on web)

1. The MacOS Go 1.15.6 installer unexpectedly installed into `/usr/local/Cellar/go` what would you recommend?
2. $GOPATH is blank
3. You mention to clone into $GOPATH/src/github.com/stellar/kelp but that path doesnt exist, should I create those folders?
4. Once running can I use Stellar-X's feed? Or is there a better feed to see Stellar's network of projects?

Thanks for your time. 

I am a senior/lead level Engineer and Angular/JS expert, if I can help with any UI/UX I would be open to help :)

**Comment by nikhilsaraf** [comment]
Hi @BenRacicot, sorry for the delayed response.

I don't think the install path for golang matters much as long as it is in your $PATH.

[This guide is helpful when setting up golang on mac](https://sourabhbajaj.com/mac-setup/Go/README.html). Maybe I can add this to the readme.

If you are looking to pull the price of a market on stellar as your price feed then you can just use "sdex" as the type. There is an example of this in the [`sample_buysell.cfg`](https://github.com/stellar/kelp/blob/b70c22c85f416fabca626380438c112e12bbb663/examples/configs/trader/sample_buysell.cfg#L49) file.

If you are looking to work on some GUI issues, maybe you can start off with one of these?
- https://github.com/stellar/kelp/issues/399
- https://github.com/stellar/kelp/issues/398

Happy to set up a call to discuss them if needed. I'm also available on keybase via direct message as `nikhilsaraf`.

**Comment by BenRacicot** [comment]
Ok setup Go and it's helloworld file is running, thanks for the link.

WHen I try to clone into the folder you recommend cloning into I'm getting:

`  kelp sudo git clone git@github.com:stellar/kelp.git
Cloning into 'kelp'...
The authenticity of host 'github.com (140.82.113.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.113.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
➜  kelp   `

**Comment by BenRacicot** [comment]
@nikhilsaraf I've finally had a moment to fix my Golang install issues. Golang installs **two** `go` folders and my path was set to the wrong one for the project!

All is running but I think I will need to discuss GUI goals/setup and how to approach those two issues.

**Comment by nikhilsaraf** [comment]
@BenRacicot since we are already in conversation on keybase and it seems this specific issue is resolved, I'm closing it out. But feel free to open any new issues that you encounter. thanks!
