### ISSUE TITLE
Old ccxtrest

### ISSUE THREAD

**Issue by ianeinser** [stellar/kelp#644]
Hello there,

is there any plan to upgrade the old ccxtrest package? it is very old package

**Comment by nikhilsaraf** [comment]
hi @ianeinser it is not currently on the roadmap since there is no clear benefit of adding support for it as we can prioritize other improvements instead.

Any reason why it is a good idea to upgrade the ccxt-rest package?

**Comment by nikhilsaraf** [comment]
closing for now to clean up github issues. feel free to comment and tag me if required.
