### ISSUE TITLE
[3] I get an error when starting 

### ISSUE THREAD

**Issue by kier0n** [stellar/kelp#651]
When I execute:
./kelp trade --botConf trader.cfg --strategy buysell --stratConf buysell.cfg
 
I get the following error . Can anybody help out on this ??

could not send startup event metric: could not post amplitude request: could not execute http request: Post https://api2.amplitude.com/2/httpapi: dial tcp [::]:443: connect: connection refused

**Comment by nikhilsaraf** [comment]
will look into this. you can run with --no-headers for now.
