### ISSUE TITLE
error in buying sub-strategy: unable to create preceding offers:

### ISSUE THREAD

**Issue by RASTecnoTI** [stellar/kelp#655]
Hi

I would like a help about the kelp strategy. I am using the balanced strategy between my own token and XLM. I setup the files trader.cfg and balanced.cfg but i receved the under message:

error in buying sub-strategy: unable to create preceding offers: unable to create new preceding offer: error: (programmer?) unable to create offer but available capacities were more than the attempted offer amounts, sellingCapacity=999.00000000, incrementalSellAmount=0.49937590, buyingCapacity=179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.00000000, incrementalBuyAmount=0.00784210

**Comment by nikhilsaraf** [comment]
@RASTecnoTI if you add more XLM into your Stellar trader account then thus should go away.

Minimum amount is 25 XLM I think, I’ll have to check the code to confirm.

If you put 40 XLM then it should cover you for a while.

**Comment by nikhilsaraf** [comment]
Closing issue as I think it addresses it, but feel free to reopen if it doesn’t fix the issue

**Comment by RASTecnoTI** [comment]
Hi

Great, I will try.

**Comment by RASTecnoTI** [comment]
Hi

The process is running now but there no orders.

2021/02/09 15:09:15 sleeping for 4m57.8927256s...
2021/02/09 15:09:16 there were no trades, leaving lastCursor value as 145700864232927233-0
2021/02/09 15:09:26 there were no trades, leaving lastCursor value as 145700864232927233-0
2021/02/09 15:09:37 there were no trades, leaving lastCursor value as 145700864232927233-0
2021/02/09 15:09:47 there were no trades, leaving lastCursor value as 145700864232927233-0
