### ISSUE TITLE
There were no traders

### ISSUE THREAD

**Issue by RASTecnoTI** [stellar/kelp#656]
Hi

I have running the program using balanced cfg but I just receive the message:

2021/02/09 15:09:15 sleeping for 4m57.8927256s...
2021/02/09 15:09:16 there were no trades, leaving lastCursor value as 145700864232927233-0
2021/02/09 15:09:26 there were no trades, leaving lastCursor value as 145700864232927233-0
2021/02/09 15:09:37 there were no trades, leaving lastCursor value as 145700864232927233-0
2021/02/09 15:09:47 there were no trades, leaving lastCursor value as 145700864232927233-0

I trying run XLM for BDIT (one new token created by myself).

BDIT
Issuer: GCRZ3AXG3LKYGWUUZHK64FEUVQ64UNEIKUCWCR5JOL336UUIIE2ZLOYG

**Comment by nikhilsaraf** [comment]
@RASTecnoTI this is just saying that there were no trades that happened against your bot. This is normal. When people trade against you it will instead show you the trades that your bot did!

closing out since it seems resolved
