### ISSUE TITLE
How to use the GUI version to set sample_balanced.cfg

### ISSUE THREAD

**Issue by garnettjing** [stellar/kelp#662]
Thank you very much for updating the GUI version, this is great！

How to use the GUI version to set sample_balanced.cfg ？

**Comment by nikhilsaraf** [comment]
that is not supported yet -- we will be finding a way to add support for the balanced strategy once we roll out the Kelp GUI out of beta status. Closing this for now as we will add a separate issue once we lay out the full roadmap
