### ISSUE TITLE
Dashboard UI tool to manage Kelp processes on your machine

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/kelp#67]
## Desired Behavior
I want to be able to visualize all the Kelp processes that I have running on my system with controls for each instance.

## Impact
The desired behavior will allow me to scale up my usage of Kelp and better manage markets.

## Feature Suggestion
We can achieve the desired behavior by having a Dashboard UI for Kelp. This can be a web page that interfaces with a server that controls various bot instances running on the machine.

## References
This feature exists in quite a few trading bots (both crypto and non-crypto). Please see the _specification_ section below for details.

### v1.0 (MVP)

1. list of all the bot instances (markets) you are running on your machine
2. create and delete bot instances
3. start and stop bots
4. delete offers for a market

### Mockup

![img_3991](https://user-images.githubusercontent.com/1028334/49535665-858ad680-f879-11e8-9192-73ede8420a9e.jpg)

### Items
- [x] bundle in React.js applications for frontend
- [x] deployment mode embeds JS assets into binary (when building with `./scripts/build.sh -d`)
- [x] local mode running from static files in filesystem (when building with `./scripts/build.sh` and running with `./bin/kelp server`)
- [x] dev mode with hot-reloading of JS code from filesystem (when building with `./scripts/build.sh` and running with `./bin/kelp server --dev`)
- [x] design mockups
- [x] frontend react components to be used
- [x] list, start, stop/delete bot instances
- [x] edit bot instances
- [x] delete bot instances
- [x] create bot instances (buysell strategy only for now)
- [x] edit form validation
- [x] add trustlines on account when saving
- [x] first pass at polishing

**Comment by nikhilsaraf** [comment]
@sgehrman created this github issue to indicate that you are working on this.

**Comment by nikhilsaraf** [comment]
v2.0 suggestions
- [ ] add iFrames to exchanges so we can view markets from within Kelp
- [ ] view trade history for account(s)

**Comment by tomquisel** [comment]
@nikhilsaraf the MVP plan looks good to me! As far as external exchanges for viewing markets, links that open new windows might work better than iframes.

**Comment by nikhilsaraf** [comment]
Check out some of the GUI frameworks mentioned here, in case they are useful: https://github.com/avelino/awesome-go/blob/master/README.md#gui

**Comment by tomquisel** [comment]
@nikhilsaraf just to be sure, your plan is to build a web UI, right? Those all look like

**Comment by nikhilsaraf** [comment]
also resource embedding frameworks: https://github.com/avelino/awesome-go#resource-embedding

**Comment by nikhilsaraf** [comment]
fyi Bruno. suggested folder ordering. the highlighted folders are what we would end up working with most.

all work should happen in the /gui/web directly, which is currently a direct instantiation of a basic create-react-app application.

see above points for the modes which you can run the GUI (`./bin/kelp server [--dev]`)

<img width="463" alt="Screen Shot 2019-04-19 at 12 15 20 PM" src="https://user-images.githubusercontent.com/1028334/56440087-39c35180-629d-11e9-8702-56940552eaf2.png">

**Comment by nikhilsaraf** [comment]
new commit to autogenerate bot config and start/stop bots: https://github.com/stellar/kelp/commit/e686d7f3f75cc47724fa0d80ab3d83af442369c0

**Comment by nikhilsaraf** [comment]
new commit to get bot info to populate bot card: https://github.com/stellar/kelp/pull/184

**Comment by nikhilsaraf** [comment]
v0.9 of Kelp is finished, currently only available on the test network for starters on SDEXX. It's still going through some alpha testing so is not available as an official release yet, but will be made available sometime this month.
