### ISSUE TITLE
"Delete" strategy should give option to exit when done

### ISSUE THREAD

**Issue by ddombrowsky** [stellar/kelp#704]
If this already exists, please explain the configuration that will achieve it, because I can't find it.

## Desired Behavior

When using the "delete" strategy, there should be an option to exit the executable after the orders are deleted.  Currently, it enters the main loop and goes back to sleep, requiring another Ctrl-C to exit.

## Impact
I would like to automate the deletion of orders without requiring user interaction.

## Feature Suggestion

Is there a way to add a configuration file to the `delete` strategy telling the executable to exit after the commands have been submitted?

**Comment by nikhilsaraf** [comment]
Hey! You can add the following command line param `--iter X` when running kelp; where X is the number of successful iterations you want the bot to run and then exit.

For example, you can run `--iter 1` with the delete strategy to have it delete the orders and then exit.

Closing out issue as I think it solves the problem. Please feel free to re-open if needed.
