### ISSUE TITLE
glide.sh domain removed

### ISSUE THREAD

**Issue by whackur** [stellar/kelp#712]
I want to get new version of kelp binary.

I can not execute follow install command.

```
Install Glide for dependency management
curl https://glide.sh/get | sh
```

http://glide.sh/ seems to be moved or deleted.

**Comment by clD11** [comment]
@nikhilsaraf this can also be close with the mod update

**Comment by nikhilsaraf** [comment]
closed because this issue is no longer relevant as off this issue being closed: https://github.com/stellar/kelp/issues/277
