### ISSUE TITLE
Fill Tracker should accommodate N errors before causing bot to exit

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/kelp#96]
## Describe the bug
The Fill Tracker does not accommodate errors and exits on the very first error. Sometimes horizon may return an incorrect response.

See [https://github.com/interstellar/kelp/issues/93](https://github.com/interstellar/kelp/issues/93) for original issue.

## Expected behavior
I think the correct behavior in this situation is for Kelp to tolerate up to N errors from the fill tracker before exiting.

## Frequency
The frequency is: Unpredictable (usually on network errors from horizon)

## Steps To Reproduce
Here are the steps to reproduce the issue (see attachments in section below):
Somehow create a network issue from the horizon call to the trades endpoint which will cause the fill tracker to fail, demonstrating the error.

## Possible Solution
This bug can be fixed by adding a new config param (or reusing `DELETE_CYCLES_THRESHOLD`).

## Your Environment
```
version: master:v1.3.0
git branch: master
git hash: e19784f
build date: 20190111T004556Z
GOOS: linux
GOARCH: amd64
```

## Context
I am unable to run v1.3.0 of the bot reliably because of this bug, or have to turn off fill tracking because of this. This means I cannot use the balanced strategy reliably in v1.3.0 because the balanced strategy depends on fill tracking as off v1.3.0

## Attachments
```
2019/01/17 18:44:02 problem encountered while running the fill tracker: error when fetching trades: error while fetching trades in SDEX (cursor=): error decoding horizon.Problem: invalid character '<' looking for beginning of value
2019/01/17 18:44:02 
2019/01/17 18:44:02 deleting all offers and then exiting...
2019/01/17 18:44:03 created 13 operations to delete offers
```

**Comment by Pedity-Luffy** [comment]
I feel reusing the `DELETE_CYCLES_THRESHOLD` will be the best solution. Too many parameters might cause more confusion in future.

**Comment by nikhilsaraf** [comment]
@Pedity-Luffy the issue in reusing it is that they need to be controlled by different time interval configs so by reusing the `DELETE_CYCLES_THRESHOLD` we would get a different time scale for trade tracking vs. for offer calculation/submission

**Comment by Pedity-Luffy** [comment]
Ah, that will cause problems. I guess in this particular case, a different config variable should be good.
